NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
install.packages("tidyverse")
install.packages("ggplot2")
library(ggplot2)
Baltimore<-subset(NEI,NEI$fips == "24510")
data<-aggregate(Emissions~type+year,Baltimore,sum)
png("plot3.png",480,480)
qplot(year,Emissions,data = data,col=type,main = "Emission Over Years by Type")+geom_line()
dev.off()